version: '1.0'
name: pipeline-20241202
displayName: open-data-v构建
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
  pr:
    branches:
      precise:
        - main
stages:
  - name: stage-9bce6ebf
    displayName: Install Node
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - ''
          - '# 安装pnpm'
          - npm install -g pnpm
          - ''
          - '# 安装依赖'
          - pnpm install
          - ''
          - '## 构建核心库'
          - pnpm run build:lib
          - ''
          - '## 安装核心库'
          - pnpm install
          - ''
          - '## 打包'
          - ''
          - pnpm run build
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./examples/dist
        caches:
          - ~/.npm
          - ~/.pnpm
        notify: []
        strategy:
          retry: '0'
          timeout: 30
  - name: stage-a5e2ba21
    displayName: checkCode
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
