import {
  ApiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudUploadOutlined,
  DashboardOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  HomeOutlined,
  LogoutOutlined,
  PictureOutlined
} from '@vicons/antd'
import {
  Airplay,
  AreaCustom,
  ChartRing,
  CheckmarkOutline,
  CloseOutline,
  Code,
  ContainerRegistry,
  ContainerSoftware,
  Course,
  DataBase,
  DataBin,
  Delete,
  Development,
  Document,
  Draggable,
  Edit,
  GroupObjects,
  Help,
  Http,
  Layers,
  LicenseMaintenance,
  LogoGithub,
  Map,
  Moon,
  OpenPanelLeft,
  OpenPanelRight,
  ProgressBarRound,
  QuadrantPlot,
  RadioButtonChecked,
  Save,
  Script,
  Sun,
  TableAlias,
  TemperatureCelsius,
  Template,
  TextAnnotationToggle,
  TextFill,
  TextIndentLess,
  TextIndentMore,
  UpdateNow,
  UserAvatar,
  ZAxis
} from '@vicons/carbon'
import {
  ArrowClockwiseDashes20Filled,
  ArrowStepBack20Regular,
  ArrowStepOver20Regular,
  ArrowTrendingLines20Regular,
  BorderNone20Regular,
  DataHistogram20Regular,
  DataPie20Regular,
  DocumentOnePage20Regular,
  FullScreenMaximize20Regular,
  Games20Regular,
  LockClosed20Regular,
  Navigation20Regular,
  PersonQuestionMark16Regular,
  Settings20Regular
} from '@vicons/fluent'
import { CubeOutline, LogoNodejs, LogoPython } from '@vicons/ionicons5'
import { AddChartSharp } from '@vicons/material'

const icons = {
  delete: Delete,
  previewOpen: EyeOutlined,
  previewClose: EyeInvisibleOutlined,
  back: ArrowStepBack20Regular,
  next: ArrowStepOver20Regular,
  clear: ClearOutlined,
  download: CloudDownloadOutlined,
  upload: CloudUploadOutlined,
  save: Save,
  axis: ZAxis,
  fullScreen: FullScreenMaximize20Regular,
  setting: Settings20Regular,
  home: HomeOutlined,
  logout: LogoutOutlined,
  template: Template,
  picture: PictureOutlined,
  expandLeft: OpenPanelLeft,
  expandRight: OpenPanelRight,
  components: ContainerRegistry,
  layers: Layers,
  page: DocumentOnePage20Regular,
  textStyle: TextFill,
  InternalData: DataBin,
  icon: Games20Regular,
  sun: Sun,
  moon: Moon,
  textIndentLess: TextIndentLess,
  textIndentMore: TextIndentMore,
  data: DataBase,
  add: AddChartSharp,
  cube: CubeOutline,
  text: TextAnnotationToggle,
  border: BorderNone20Regular,
  rotation: ArrowClockwiseDashes20Filled,
  chartLine: ArrowTrendingLines20Regular,
  chartHistogram: DataHistogram20Regular,
  chartPie: DataPie20Regular,
  lock: LockClosed20Regular,
  dashboard: DashboardOutlined,
  refresh: UpdateNow,
  user: UserAvatar,
  api: ApiOutlined,
  code: Code,
  group: GroupObjects,
  doc: Document,
  http: Http,
  nodeJs: LogoNodejs,
  github: LogoGithub,
  python: LogoPython,
  development: Development,
  help: Help,
  question: PersonQuestionMark16Regular,
  progress: ProgressBarRound,
  table: TableAlias,
  thermometer: TemperatureCelsius,
  custom: AreaCustom,
  map: Map,
  other: Draggable,
  button: RadioButtonChecked,
  navigation: Navigation20Regular,
  script: Script,
  preview: Airplay,
  edit: Edit,
  close: CloseOutline,
  check: CheckmarkOutline,
  attr: QuadrantPlot,
  license: LicenseMaintenance,
  course: Course,
  intro: ChartRing,
  container: ContainerSoftware
}

export default icons
