name: main

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: '16'
          cache: pnpm


      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 node 版本
          version: '7'

      # 安装依赖
      - name: Install dependencies
        run: pnpm bootstrap --frozen-lockfile

      # 检查代码
      - name: Lint Code
        run: pnpm run lint

      # 运行构建脚本
      - name: Build frontend
        run: pnpm run build
